baseURL = "https://kevinbourgeois.github.io/labVeille"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Kevin Bourgeois"
theme = "lightbi2"


[Params]
selfHosted = true
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"
hideAuthor = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Kevin Bourgeois"



[[menu.main]]
    name = "About"
    url = "/content/about/"
    weight = 5



